# Automatically updated by the winget bot at 2021/Jun/28
PackageIdentifier: Nlitesoft.NTLite
PackageVersion: 2.1.2.8047
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://downloads.ntlite.com/files/NTLite_setup_x64.exe
  InstallerSha256: D2A0D7D39740B11E111BCDD69901DD0F8C0E54FE3DD7E7B9B7231AF63C93A31A
  UpgradeBehavior: install
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://downloads.ntlite.com/files/NTLite_setup_x86.exe
  InstallerSha256: 689141E3EA9510B956D0A493480634EC1ED54A663E58D8D52F4321201EC8359A
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
