# Created using wingetcreate

PackageIdentifier: VoodooSoft.VoodooShield
PackageVersion: 6.55
PackageLocale: en-US
Publisher: VoodooSoft, LLC
PackageName: VoodooShield
License: Copyright © VoodooSoft, LLC 2011-2021
ShortDescription: A mail and browser malware blocker.
ManifestType: defaultLocale
ManifestVersion: 1.0.0
