# Created using wingetcreate 0.2.0.29
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Spotify.Spotify
PackageVersion: 1.1.62.583.gdac868ed
MinimumOSVersion: 10.0.0.0
Platform:
- Windows.Desktop
InstallModes:
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: neutral
  InstallerType: exe
  Scope: user
  InstallerUrl: https://download.scdn.co/SpotifySetup.exe
  InstallerSha256: 4FE8735BD23743D7C7BAB8CBECB3FB6DBFD49C768E17F67DBD2EF7D3AEE9EB87
  InstallerSwitches:
    Silent: ' '
    SilentWithProgress: ' '
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

