# Created using wingetcreate 0.2.0.29
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.0.0.schema.json

PackageIdentifier: Spotify.Spotify
PackageVersion: 1.1.62.583.gdac868ed
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.0.0

