# Created using wingetcreate 0.2.0.29
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: UnicornSoft.UnicornHTTPS
PackageVersion: 1.2.64.92
PackageLocale: ko-KR
Publisher: Unicorn Soft
PublisherUrl: https://www.unicorn-soft.com/
PrivacyUrl: https://www.unicorn-soft.com/kr-privacy-unicorn
PackageName: 유니콘 HTTPS
License: Copyright(C) 2019 Unicorn Soft
ShortDescription: Unicorn HTTPS protects internet conection from goverment wiretapping or ISP censorship.
ManifestType: defaultLocale
ManifestVersion: 1.0.0
