# Created using wingetcreate 0.2.0.29
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: UnicornSoft.UnicornHTTPS
PackageVersion: 1.2.64.92
Installers:
- Architecture: x86
  InstallerType: nullsoft
  InstallerUrl: https://unicornhttps-production.s3.ap-northeast-2.amazonaws.com/unicornhttps/v1/hello/windows/unicorn-https-setup.exe
  InstallerSha256: F664C351E920737BEFCB7D542B02977F66154DAB4941E5D46E268884F32506D3
ManifestType: installer
ManifestVersion: 1.0.0
