PackageIdentifier: WhatsApp.WhatsApp
PackageVersion: 2.2123.8
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x64
  InstallerType: exe
  InstallerUrl: https://web.whatsapp.com/desktop/windows/release/x64/WhatsAppSetup.exe
  InstallerSha256: 05D34F547BD19DF5F29A43E865E91A0CE5472D78BE53534C3EFA2CE9509A22AA
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
- Architecture: x86
  InstallerType: exe
  InstallerUrl: https://web.whatsapp.com/desktop/windows/release/ia32/WhatsAppSetup.exe
  InstallerSha256: DBA34CCE98B7C8D0CF18A65C21EE188D0DB698E45C8BE5B92763B59FA2C60D67
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

