# Created using wingetcreate 0.2.0.29
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: KakaoEnterprise.KakaoWork
PackageVersion: 1.7.0.2191
PackageLocale: ko-KR
Publisher: Kakao Enterprise Corp
PublisherUrl: https://www.kakaoenterprise.com/
PrivacyUrl: https://www.kakaoenterprise.com/external/privacy
PackageName: Kakao Work
PackageUrl: https://www.kakaowork.com/
License: © Kakao Enterprise Corp.
ShortDescription: Kakao Work is comprehensive business messenger platform by Kakao Enterprise Corp.
ManifestType: defaultLocale
ManifestVersion: 1.0.0
