# Automatically updated by the winget bot at 2021/Jul/07
PackageIdentifier: Tutanota.Tutanota
PackageVersion: 3.84.10.1558
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: neutral
  InstallerType: nullsoft
  InstallerUrl: https://mail.tutanota.com/desktop/tutanota-desktop-win.exe
  InstallerSha256: BF9CF7E1C291C8F99D41A8DCAC097E4D2D3BAF7D770BDD331F0A37D777113224
  Scope: user
  InstallerLocale: en-US
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
