# Automatically updated by the winget bot at 2021/Jun/26
PackageIdentifier: Tutanota.Tutanota
PackageVersion: 3.84.7.1543
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: neutral
  InstallerType: nullsoft
  InstallerUrl: https://mail.tutanota.com/desktop/tutanota-desktop-win.exe
  InstallerSha256: 6D0241D5F2025CA1D5CB7AD6F5658950B83C675E05EC2513D21B4909367696A3
  Scope: user
  InstallerLocale: en-US
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
