# Automatically updated by the winget bot at 2021/Jul/02
PackageIdentifier: Wargaming.GameCenter
PackageVersion: 21.04.00.5527
InstallerSwitches:
  Silent: /silent
  SilentWithProgress: /silent
Installers:
- Architecture: x86
  InstallerType: exe
  InstallerUrl: https://redirect.wargaming.net/WoT/latest_web_install_na?
  InstallerSha256: E575BD58355D5C76F0445805A0E91489AF351F6F56BA006F093EBA8A979120CF
ManifestType: installer
ManifestVersion: 1.0.0
