PackageIdentifier: LutzRoeder.Netron
PackageVersion: 4.9.9
Platform:
- Windows.Desktop
InstallModes:
- silent
- silentWithProgress
Installers:
- Architecture: x86
  Scope: user
  InstallerType: nullsoft
  InstallerUrl: https://github.com/lutzroeder/netron/releases/download/v4.9.9/Netron-Setup-4.9.9.exe
  InstallerSha256: 601C94771AD9419519ECA5E888C1E8FE897A042EFC87999D6CF8D6E48AA5543C
  InstallerLocale: en-US
  InstallerSwitches:
    Custom: /NORESTART
  UpgradeBehavior: install
- Architecture: arm64
  Scope: user
  InstallerType: nullsoft
  InstallerUrl: https://github.com/lutzroeder/netron/releases/download/v4.9.9/Netron-Setup-4.9.9.exe
  InstallerSha256: 601C94771AD9419519ECA5E888C1E8FE897A042EFC87999D6CF8D6E48AA5543C
  InstallerLocale: en-US
  InstallerSwitches:
    Custom: /NORESTART
  UpgradeBehavior: install
FileExtensions:
- armnn
- caffemodel
- cmf
- dnn
- h5
- hd5
- hdf5
- keras
- lite
- mar
- meta
- mlmodel
- mlpackage
- mnn
- model
- nn
- onnx
- paddle
- param
- pb
- pbtxt
- pdmodel
- pdparams
- prototxt
- pt
- pth
- rknn
- t7
- tfl
- tflite
- tmfile
- uff
- xmodel
ManifestType: installer
ManifestVersion: 1.0.0
