PackageIdentifier: Wondershare.PDFelement
PackageVersion: 8.2.2
PackageLocale: en-US
Publisher: Wondershare
PackageName: Wondershare PDFelement
License: Copyright © 2021 Wondershare.
LicenseUrl: https://www.wondershare.com/company/end-user-license-agreement.html
PublisherUrl: "https://pdf.wondershare.com/"
PrivacyUrl: "https://www.wondershare.com/privacy.html"
Tags: 
 - "PDF editing"
 - "Wondershare"
 - "pdf"
ShortDescription: "Get started with the easiest way to manage PDFs with PDFelement across desktop, mobile and web."
Installers:
 - Architecture: "x64"
   InstallerType: "inno"
   InstallerUrl: "http://download.wondershare.com/cbs_down/pdfelement-pro_full5239.exe"
   InstallerSha256: 6523654C4775A5DDA362E8A186D3C6730E882B3C501D19D8328E40FFB4842BDD
ManifestType: "singleton"
ManifestVersion: "1.0.0"
