# Automatically updated by the winget bot at 2021/Jun/30
PackageIdentifier: Doist.Todoist
PackageVersion: 1.0.0
Installers:
- Architecture: neutral
  InstallerType: nullsoft
  InstallerUrl: https://todoist.com/windows_app
  InstallerSha256: F5A94C16DDBF4A1F1089E2CC8A8B03244318F4E707E6C20E03F570050A4E2EB1
ManifestType: installer
ManifestVersion: 1.0.0
