# Created using wingetcreate 0.2.0.29
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: NHNCorporation.Dooray!Messenger
PackageVersion: 1.1.5.1
PackageLocale: ko-KR
Publisher: NHN Corporation
PackageName: Dooray! Messenger
License: © NHN Corp. All rights reserved.
ShortDescription: Dooray! Messenger is a web-based collaboration service that integrates advanced cloud technology and security system from NHN.
ManifestType: defaultLocale
ManifestVersion: 1.0.0

