# Automatically updated by the winget bot at 2021/Jul/14
PackageIdentifier: SmartSoft.SmartFTP
PackageVersion: 10.0.2902.0
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x64
  InstallerType: msi
  InstallerUrl: https://static.smartftp.com/static/Products/Client/x64/SmartFTP.msi
  InstallerSha256: AD8D2688C0F28F2B233C3EA8B8EF40692801F3C75F7498CB0486419DEC3E41FE
  ProductCode: "{70C5E7D2-65B7-4E9B-931D-D4BB09760CFC}"
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
