# Automatically updated by the winget bot at 2021/Jul/14
PackageIdentifier: TrackerSoftware.PDF-XChangePRO
PackageVersion: 9.1.355.0
PackageLocale: en-US
Publisher: Tracker Software Products (Canada) Ltd.
PackageName: PDF-XChange PRO
License: Copyright (c) Tracker Software Products (Canada) Ltd.
ShortDescription: All the features of PDF-XChange Editor Plus, PDF-Tools and PDF-XChange Standard in one economical bundle.
ManifestType: defaultLocale
ManifestVersion: 1.0.0
