PackageIdentifier: "Wondershare.Filmora"
PackageVersion: "10.5"
PackageLocale: "en-US"
Publisher: Wondershare Software
PackageName: "Wondershare Filmora"
License: Copyright © 2021 Wondershare.
LicenseUrl: https://www.wondershare.com/company/end-user-license-agreement.html
PublisherUrl: "https://filmora.wondershare.com/"
PrivacyUrl: "https://www.wondershare.com/privacy.html"
Tags: 
 - "Video Editor"
 - "Wondershare"
 - "Filmora"
ShortDescription: "Intuitive video editing"
Installers:
 - Architecture: "x64"
   InstallerType: "inno"
   InstallerUrl: "http://download.wondershare.com/cbs_down/filmora_64bit_full846.exe"
   InstallerSha256: DF591E829B3E015AC38F0AF6F9531B3D2236DA7B8A4369A1B6B2EDD08DA6DA40
ManifestType: "singleton"
ManifestVersion: "1.0.0"
