# Automatically updated by the winget bot at 2021/Jul/02
PackageIdentifier: Project64.Project64
PackageVersion: 3.0.1.5664
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x86
  InstallerType: inno
  InstallerUrl: https://www.pj64-emu.com/file/setup-project64-3-0-0-5632-f83bee9/
  InstallerSha256: 591AE9FE2C073D452F8EB08CBE5A9705224F131EADEB553E270A50A11592FD11
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
