# Automatically updated by the winget bot at 2021/Jun/17
PackageIdentifier: Autodesk.Fusion360
PackageVersion: latest
PackageName: Fusion 360
Publisher: Autodesk
License: Copyright (c) Autodesk Inc.
ShortDescription: Integrated CAD, CAM, and PCB software
PackageUrl: https://www.autodesk.com/products/fusion-360/overview
Installers:
- Architecture: x86
  InstallerUrl: https://dl.appstreaming.autodesk.com/production/installers/Fusion%20360%20Admin%20Install.exe
  InstallerSha256: 0C0DC28050BF56CA9F9049596D9B37D43C212A187B1646DD4AD63797B1D46946
  InstallerType: exe
  InstallerSwitches:
    Silent: --quiet
    SilentWithProgress: --quiet
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
