PackageIdentifier: "Wondershare.DemoCreator"
PackageVersion: 5.0.0
PackageLocale: "en-US"
Publisher: Wondershare Software
PackageName: "Wondershare DemoCreator"
License: Copyright © 2021 Wondershare.
LicenseUrl: https://www.wondershare.com/company/end-user-license-agreement.html
PublisherUrl: "https://dc.wondershare.com/"
PrivacyUrl: "https://www.wondershare.com/privacy.html"
Tags: 
 - "Video Editing"
 - "Wondershare"
 - "DemoCreator"
 - "Screen Recording"
ShortDescription: "DemoCreator makes it simple to capture video demos, tutorials, presentations, games and edit them quickly like a Pro."
Installers:
 - Architecture: "x64"
   InstallerType: "inno"
   InstallerUrl: "https://download.wondershare.com/cbs_down/democreator_full7743.exe"
   InstallerSha256: CE7EA8BFD37341FB701FF473133C99E1B42249C2B9E41892F7BEE0CB50E9B4D2
ManifestType: "singleton"
ManifestVersion: "1.0.0"
