# Created using wingetcreate 0.2.0.29
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: SmartSoft.SmartFTP
PackageVersion: 10.0.2900.0
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x64
  InstallerType: msi
  InstallerUrl: https://www.smartftp.com/get/SmartFTP64.msi
  InstallerSha256: 627EE52AE5B993B3509F01DD299D797E97BD28DA63CA8B27D249026F554B05DE
  ProductCode: "{FD54FC59-A336-452D-8943-1135C12FEC36}"
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

