# Created using wingetcreate 0.2.0.29
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: TorProject.TorBrowser
PackageVersion: 10.0.18
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  InstallLocation: /D="<INSTALLPATH>"
Protocols:
- http
- https
FileExtensions:
- htm
- html
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://www.torproject.org/dist/torbrowser/10.0.18/torbrowser-install-win64-10.0.18_en-US.exe
  InstallerSha256: F9C16870A6427BB91CEA34828D57B86D0A9EA1EEA58B5E86EA734AE8469149C5
  UpgradeBehavior: install
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://www.torproject.org/dist/torbrowser/10.0.18/torbrowser-install-10.0.18_en-US.exe
  InstallerSha256: 2617293110DF48AB1D878A418F9FFA9468A7F31C13170487226DCCE593DA7DFE
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

